apiVersion: batch/v1
kind: Job
metadata:
  name: gatling
spec:
  template:
    metadata:
      name: gatling
    spec:
      restartPolicy: Never
      containers:
        - name: gatling
          image: openig-gatling
          imagePullPolicy: IfNotPresent
          command: ["sbt",  "clean", "gatling:test"]
          volumeMounts:
            - name: perftest-results
              mountPath: /opt/gatling/results
      # Note that a hostPath volume will only work on a single node cluster- like minikube
      volumes:
        - name: perftest-results
          hostPath:
            path: /data/perftest-results