version: "3.4"
services:
  db:
    restart: always # OS起動時にコンテナを自動起動
    build: ./tools/mysql
    ports:
      - 3306:3306
    env_file: ./tools/mysql/.env # 環境変数に外部ファイルを指定
  redis:
    image: redis:3.2.4-alpine
    restart: always # OS起動時にコンテナを自動起動
    ports:
      - "6379:6379"
  aerpsike:
    restart: always # OS起動時にコンテナを自動起動
    image: aerospike
    ports:
      - "3000:3000"
    volumes:
      - ./tools/aerpsike/data:/opt/aerpsike/data
      - ./tools/aerpsike/conf:/etc/aerpsike
    command: [ "--config-file","/etc/aerospike/aerospike.conf"]
    ulimits:
      nproc: 65535
      nofile:
        soft: 64000
        hard: 64000
  boot:
    image: bambootuna/loadtest:latest
    restart: always # OS起動時にコンテナを自動起動
    ports:
      - 8080:8080
      - 8999:8999
    environment:
      - JVM_HEAP_MIN=1g
      - JVM_HEAP_MAX=1g
      - JVM_META_MAX=512m
      - JMX_PORT=8999
#      - DATADOG_HOSTNAME=datadog
#      - DATADOG_PORT=8125
      - LOADTEST_REDIS_HOST=redis
    depends_on:
      - db
      - redis