version: "3.4"
services:
  mysql-budget-db:
    restart: always # OS起動時にコンテナを自動起動
    build: ./tools/mysql
    ports:
      - 3306:3306
    env_file: ./tools/mysql/.env # 環境変数に外部ファイルを指定
  redis-user-info-master:
    image: redis:3.2.4-alpine
    restart: always # OS起動時にコンテナを自動起動
    ports:
      - 6379:6379
  redis-advertiser-id-master:
    image: redis:3.2.4-alpine
    restart: always # OS起動時にコンテナを自動起動
    ports:
      - 6380:6379
  boot:
    image: bambootuna/loadtest:latest
    restart: always # OS起動時にコンテナを自動起動
    ports:
      - 8080:8080
      - 8999:8999
    environment:
      - JVM_HEAP_MIN=1g
      - JVM_HEAP_MAX=1g
      - JVM_META_MAX=512m
      - JMX_PORT=8999
      - RDB_HOST=mysql-budget-db
      - USER_INFO_REDIS_HOST=redis-user-info-master
      - ADVERTISER_ID_REDIS_HOST=redis-advertiser-id-master

    depends_on:
      - mysql-budget-db
      - redis-user-info-master
      - redis-advertiser-id-master