apiVersion: v1
kind: Service
metadata:
  name: loadtest-service
  labels:
    app: loadtest
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: loadtest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadtest-deployment
  labels:
    app: loadtest
spec:
  replicas: 20
  selector:
    matchLabels:
      app: loadtest
  template:
    metadata:
      labels:
        app: loadtest
    spec:
      containers:
      - name: loadtest
        image: IMAGE_NAME
        #localのdocker imageを使用する際に必要
        #imagePullPolicy: Never
        env:
          - name: DATADOG_PORT
            value: "8125"
          - name: JVM_HEAP_MIN
            value: "524M"
          - name: JVM_HEAP_MAX
            value: "1024M"
          - name: JVM_META_MAX
            value: "512M"
          - name: RDB_HOST
            value: "db-service-mysql"
          - name: RDB_PORT
            value: "3306"
          - name: LOADTEST_RDB_USER
            valueFrom:
              secretKeyRef:
                name: dbsecret
                key: user
          - name: LOADTEST_RDB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: dbsecret
                key: password
          - name: RDB_DATABASE
            valueFrom:
              secretKeyRef:
                name: dbsecret
                key: databese_name
          - name: LOADTEST_REDIS_HOST
            value: "redis-service-master"
          - name: AEROSPIKE_HOST
            value: "aerospike-service"
          - name: DATADOG_HOSTNAME
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
        resources:
          requests:
            memory: "512Mi"
            cpu: "361m"
          limits:
            memory: "512Mi"
            cpu: "361m"
        ports:
        - containerPort: 8080
