apiVersion: v1
kind: Service
metadata:
  name: loadtest-service
  labels:
    app: loadtest
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: loadtest
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: loadtest-deployment
  labels:
    app: loadtest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: loadtest
  template:
    metadata:
      labels:
        app: loadtest
    spec:
      containers:
      - name: loadtest
        image: loadtest-local-k8s:latest
        #localのdocker imageを使用する際に必要
        imagePullPolicy: Never
        env:
          - name: RDB_HOST
            value: "db"
          - name: RDB_PORT
            value: "3306"
          - name: LOADTEST_RDB_USER
            valueFrom:
              secretKeyRef:
                name: dbsecret
                key: user
          - name: LOADTEST_RDB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: dbsecret
                key: password
          - name: RDB_DATABASE
            value: "loadtest"
        resources:
          requests:
            memory: 512Mi
        ports:
        - containerPort: 80
