#本番運用時はリポジトリに上げないようにするべし！

apiVersion: v1
kind: Secret
metadata:
  name: dbsecret
type: Opaque
data:
  #base64でエンコードしておく必要あり echo -n "string" | base64
  #root
  root_password: cm9vdA==
  #BambooTuna
  user: QmFtYm9vVHVuYQ==
  #pass
  password: cGFzcw==
  #loadtest
  databese_name: bG9hZHRlc3Q=