apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: loadtest-deployment
  labels:
    app: loadtest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: loadtest
  template:
    metadata:
      labels:
        app: loadtest
    spec:
      containers:
      - name: loadtest
        image: docker.io/DOCKER_TAG
        ports:
        - containerPort: 80
