apiVersion: batch/v1
kind: Job
metadata:
  name: gatling-runner
spec:
  backoffLimit: 1
  parallelism: 1
  completions: 1
  template:
    metadata:
      labels:
        name: gatling-runner
    spec:
      containers:
        - name: gatling-runner
          image: gcr.io/cyberagent-320/cyberagenthack/gatling-runner:6be4f7e5ad5018ff352912a1f1a57bef4bddfe7c
          env:
            - name: GATLING_BASE_URL
              value: "http://34.84.137.136:8080"
            - name: GATLING_USERS
              value: "100"
          resources:
            limits:
              cpu: 5000m
              memory: 1000Mi
            requests:
              cpu: 5000m
              memory: 1000Mi
      restartPolicy: Never