apiVersion: batch/v1
kind: Job
metadata:
  name: gatling-runner
spec:
  backoffLimit: 1
  parallelism: 1
  completions: 1
  template:
    metadata:
      labels:
        name: gatling-runner
    spec:
      containers:
        - name: gatling-runner
          image: GATLING_IMAGE_NAME
          resources:
            limits:
              cpu: 500m
              memory: 2500Mi
            requests:
              cpu: 500m
              memory: 2500Mi
      restartPolicy: Never