apiVersion: batch/v1
kind: Job
metadata:
  name: gatling-runner
spec:
  backoffLimit: 1
  parallelism: 1
  completions: 1
  template:
    metadata:
      labels:
        name: gatling-runner
    spec:
      containers:
        - name: gatling-runner
          image: GATLING_IMAGE_NAME
          env:
            - name: GATLING_BASE_URL
              value: "http://35.200.14.159:8080"
            - name: GATLING_USERS
              value: "500"
          resources:
            limits:
              cpu: 1000m
              memory: 1000Mi
            requests:
              cpu: 1000m
              memory: 1000Mi
      restartPolicy: Never