# Scala CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/sample-config/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo

    environment:
      SBT_VERSION: 1.2.8
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.sbt" }}
            - v1-dependencies-
      - run: cat /dev/null | sbt test:compile
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies--{{ checksum "build.sbt" }}
      - run: cat /dev/null | sbt test:test

  staging:
    docker:
      - image: hashicorp/terraform:0.12.6
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Create gcp credential
          command: |
            echo $GCLOUD_SERVICE_KEY | base64 -d > ./account.json
          working_directory: ~/project/infrastructure/staging/gcp/terraform
      - run:
          name: init terraform
          command: |
            sh ./import.sh
          working_directory: ~/project/infrastructure/staging/gcp/terraform
      - run:
          name: plan terraform
          command: terraform plan -var-file=../gcloud-env
          working_directory: ~/project/infrastructure/staging/gcp/terraform
      - run:
          name: apply terraform
          command: terraform apply -auto-approve -var-file=../gcloud-env
          working_directory: ~/project/infrastructure/staging/gcp/terraform

workflows:
  version: 2
  build-n-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: feature/destroy-gcp-source
      - staging:
          requires:
            - build
          filters:
            branches:
              only: feature/destroy-gcp-source
