# Scala CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/sample-config/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo

    environment:
      SBT_VERSION: 1.2.8
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.sbt" }}
            - v1-dependencies-

      - run: cat /dev/null | sbt test:compile

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies--{{ checksum "build.sbt" }}

      - run: cat /dev/null | sbt test:test
  deploy:
    docker:
      - image: docker:17.07.0-ce-git
    steps:
      - checkout

      - setup_remote_docker

      - run:
          command: docker build -t $(echo `${CIRCLE_PROJECT_REPONAME}/${CIRCLE_PROJECT_USERNAME}:${CIRCLE_TAG}` | sed 's/.\+/\L\0/') .
      - run:
          command: docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
      - run:
          command: docker push $(echo `${CIRCLE_PROJECT_REPONAME}/${CIRCLE_PROJECT_USERNAME}:${CIRCLE_TAG}` | sed 's/.\+/\L\0/')

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^[0-9]+\.[0-9]+\.[0-9]+$/