# Scala CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/sample-config/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo

    environment:
      SBT_VERSION: 1.2.8
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - setup_remote_docker

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.sbt" }}
            - v1-dependencies-

      - run: cat /dev/null | sbt test:compile

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies--{{ checksum "build.sbt" }}

      - run: cat /dev/null | sbt test:test

      - run: sbt docker:publishLocal

  staging:
    docker:
      - image: hashicorp/terraform:0.12.6
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Create gcp credential
          command: |
            echo $GCLOUD_SERVICE_KEY | base64 -d > ${HOME}/account.json
      - run:
          name: init terraform
          command: |
            . ../env
            terraform -v
            terraform init
            terraform import google_project.my_project ${GOOGLE_PROJECT_ID}
            terraform import -var-file=../env google_compute_network.default ${GOOGLE_PROJECT_ID}
            terraform import -var-file=../env google_compute_subnetwork.default ${GOOGLE_PROJECT_ID}
            terraform import -var-file=../env google_container_cluster.default ${GOOGLE_PROJECT_ID}/${GOOGLE_COMPUTE_ZONE}/${GOOGLE_CLUSTER_NAME}
            terraform import -var-file=../env google_compute_global_address.ip_address ${GOOGLE_PROJECT_ID}/${GOOGLE_PROJECT_ID}-static-ip
#            terraform refresh -var-file=../env
          working_directory: ~/project/infrastructure/staging/gcp/terraform
      - run:
          name: plan terraform
          command: terraform plan -var-file=../env
          working_directory: ~/project/infrastructure/staging/gcp/terraform
      - run:
          name: apply terraform
          command: terraform apply -auto-approve -var-file=../env
          working_directory: ~/project/infrastructure/staging/gcp/terraform

  deploy:
    docker:
      - image: google/cloud-sdk
    environment:
      DEPLOYMENT_YML: deployment.yml
      SERVICE_YML: service.yml
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Docker build and push
          command: |
            export DOCKER_TAG=`echo "${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}:latest" | tr '[:upper:]' '[:lower:]'`
            docker build -t ${DOCKER_TAG} .
            docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
            docker push $DOCKER_TAG
      - run:
          name: Create gcp credential
          command: |
            echo $GCLOUD_SERVICE_KEY | base64 -d > ${HOME}/account.json
      - run:
          name: Deploy to GKE
          command: |
            sh setup-k8s.sh
          working_directory: ~/project/infrastructure/staging/gcp/k8s
workflows:
  version: 2
  build-n-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - staging:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - deploy:
          requires:
            - staging
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/