# Scala CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/sample-config/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo

    environment:
      SBT_VERSION: 1.2.8
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.sbt" }}
            - v1-dependencies-
      - run: cat /dev/null | sbt test:compile
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies--{{ checksum "build.sbt" }}
      - run: cat /dev/null | sbt test:test

  staging:
    docker:
      - image: hashicorp/terraform:0.12.6
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Create gcp credential
          command: |
            echo $GCLOUD_SERVICE_KEY | base64 -d > ./account.json
          working_directory: ~/project/infrastructure/staging/gcp/terraform
      - run:
          name: init terraform
          command: |
            sh ./import.sh
          working_directory: ~/project/infrastructure/staging/gcp/terraform
      - run:
          name: plan terraform
          command: terraform plan -var-file=../gcloud-env
          working_directory: ~/project/infrastructure/staging/gcp/terraform
      - run:
          name: apply terraform
          command: terraform apply -auto-approve -var-file=../gcloud-env
          working_directory: ~/project/infrastructure/staging/gcp/terraform

  push:
    docker:
      - image: circleci/openjdk:8-jdk
    environment:
      SBT_VERSION: 1.2.8
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Create gcp credential
          command: |
            echo $GCLOUD_SERVICE_KEY | base64 -d > ${HOME}/account.json
      - run:
          name: Login docker
          command: |
            cat ${HOME}/account.json | docker login -u _json_key --password-stdin https://gcr.io
      - run:
          name: Docker build and push
          command: |
            . ~/project/infrastructure/staging/gcp/gcloud-env
            export APP_IMAGE=`echo "${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}" | tr '[:upper:]' '[:lower:]'`
            export IMAGE_NAME=gcr.io/${GOOGLE_PROJECT_ID}/${APP_IMAGE}

            export GATLING_IMAGE=`echo "${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}-gatling" | tr '[:upper:]' '[:lower:]'`
            export GATLING_IMAGE_NAME=gcr.io/${GOOGLE_PROJECT_ID}/${GATLING_IMAGE}

            sbt docker:publishLocal
            sbt gatling-test/docker:publishLocal

            docker tag ${APP_IMAGE}:latest ${IMAGE_NAME}:latest
            docker push ${IMAGE_NAME}

            docker tag ${GATLING_IMAGE}:latest ${GATLING_IMAGE_NAME}:latest
            docker push ${GATLING_IMAGE_NAME}

            cd tools/mysql
            docker build . -t gcr.io/${GOOGLE_PROJECT_ID}/mysql:latest
            docker push gcr.io/${GOOGLE_PROJECT_ID}/mysql:latest

  deploy:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install helm
          command: |
            curl https://storage.googleapis.com/kubernetes-helm/helm-v2.12.3-linux-amd64.tar.gz | tar zx linux-amd64/helm
            mv linux-amd64/helm /usr/local/bin/helm; rm -rf linux-amd64
      - run:
          name: Deploy to GKE
          command: |
            . ~/project/infrastructure/staging/gcp/gcloud-env

            export DOCKER_TAG=`echo "${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}:latest" | tr '[:upper:]' '[:lower:]'`
            export IMAGE_NAME=gcr.io/${GOOGLE_PROJECT_ID}/${DOCKER_TAG}

            export DB_IMAGE=gcr.io/${GOOGLE_PROJECT_ID}/mysql
            export DB_TAG=latest

            echo $GCLOUD_SERVICE_KEY | base64 -d > ${HOME}/account.json
            gcloud auth activate-service-account --key-file ${HOME}/account.json
            gcloud --quiet config set project $GOOGLE_PROJECT_ID
            gcloud --quiet config set compute/region $GOOGLE_COMPUTE_REGION
            gcloud --quiet config set compute/zone $GOOGLE_COMPUTE_ZONE
            gcloud --quiet container clusters get-credentials $GOOGLE_CLUSTER_NAME

            cd ~/project/infrastructure/staging/gcp/k8s
            sh ./setup-k8s.sh

workflows:
  version: 2
  build-n-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - staging:
          requires:
            - build
          filters:
            branches:
              only:
                - develop
                - /feature\/develop\/.+/
      - push:
          requires:
            - staging
          filters:
            branches:
              only:
                - develop
                - /feature\/develop\/.+/
      - deploy:
          requires:
            - push
          filters:
            branches:
              only:
                - develop
                - /feature\/develop\/.+/
