apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: loadtest
spec:
  replicas: 2
  template:
    metadata:
      labels:
        run: loadtest
    spec:
      containers:
        - name: loadtest
          image: gcr.io/loadtest-249613/loadtest:COMMIT_SHA
          ports:
            - containerPort: 80