steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Image'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/$_IMAGE_MANE:$SHORT_SHA', '.', '-f', '../../../Dockerfile']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push to GCR'
    args: ['push', 'gcr.io/$PROJECT_ID/$_IMAGE_MANE:$SHORT_SHA']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Edit Deployment Manifest'
    entrypoint: 'bash'
    args:
      - '-c'
      - sed -i -e 's/PROJECT_ID/${PROJECT_ID}/' k8s/deployment.yml
      - sed -i -e 's/IMAGE_MANE/${_IMAGE_MANE}/' k8s/deployment.yml
      - sed -i -e 's/COMMIT_SHA/${SHORT_SHA}/' k8s/deployment.yml

  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'Apply Deployment Manifest'
    args: ['apply', '-f', './k8s/deployment.yml']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=$_ZONE'
      - 'CLOUDSDK_CONTAINER_CLUSTER=$PROJECT_ID'

  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'Apply Service Manifest'
    args: ['apply', '-f', './k8s/service.yml']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=$_ZONE'
      - 'CLOUDSDK_CONTAINER_CLUSTER=$PROJECT_ID'
